version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./frontend/.env.sample
    stdin_open: true
    tty: true
    depends_on:
      - mongodb

  backend:
    container_name: backend
    build: ./Backend
    env_file:
      - ./Backend/.env.sample
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    

volumes:
  logs:
